// String changedFilePaths = ''

// def atcost = new ArrayList<String>()
// def nutanix = new ArrayList<String>()

pipeline{
    agent any
    stages{
        stage('Git Checkout'){
           steps{
            checkout([
                $class: 'GitSCM',
                branches: [[name: '*/407-test-changed-files-from-CWF']],
                extensions: [],
                userRemoteConfigs: [[
                    credentialsId: '6e8e3064-2329-46fe-bfa3-b1c54f17e885',
                    url: 'https://github.com/Calance-US/calance-services-helm-values.git'
                ]]
            ])
           }
        }
        stage('Find the cluster to which Changed Files will be applied'){
            
                // changedFilePaths = ${CHANGED_FILES}
                // changedFilePaths = changedFilePaths.split(',')
                // for (int i = 0; i < changedfilePaths.size(); i++){
                //     if (${changedfilePaths[i]}.contains('jenkins')){
                //         nutanix.add(${changedfilePaths[i]})
                //     } else{
                //         atcost.add(${changedfilePaths[i]})
                //     }
                // }
            steps{
                echo $CHANGED_FILES
            }
                
                
            
            
        }
        
    }
}
