name: Calance generic CI-CD
on:
  workflow_call:
    secrets:
      NAMESPACE:
        required: true
        description: 'Enter the application namespace:'
      JENKINS_URL:
        required: true
        description: 'Jenkins URL'
      JENKINS_USER:
        required: true
        description: 'Jenkins USER'
      JENKINS_TOKEN:
        required: true
        description: 'Jenkins USER'
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+-rc[0-9]
      - v[0-9]+.[0-9]+.[0-9]+


jobs:
  build-docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    outputs:
      version: ${{ steps.version.outputs.build_version }}
      cluster_environment: ${{ steps.cluster_environment.outputs.cluster_environment }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            ghcr.io/${{ github.repository }}
          tags: |
            type=semver,pattern={{version}}

      - name: Setting application version
        id: version
        run: |
          echo "::set-output name=build_version::${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.version'] }}"
      - name: Identifying cluster in which application should be deployed
        id: cluster_environment
        run: |
          if [[ "${{fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.version']}}" =~ .*-rc[0-9] ]]; then
            echo '::set-output name=cluster_environment::testing'
          else
            echo '::set-output name=cluster_environment::production'
          fi

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy-to-kubernetes:
    needs: build-docker
    uses: Calance-US/calance-workflows/.github/workflows/deploy.yml@test
    with:
      repository_name: ${{ github.event.repository.name }}
      version: ${{ needs.build-docker.outputs.version }}
      cluster_environment: ${{ needs.build-docker.outputs.cluster_environment }}
    secrets:
      namespace: ${{ secrets.NAMESPACE }}
      JENKINS_URL: ${{ secrets.JENKINS_URL }}
      JENKINS_USER: ${{ secrets.JENKINS_USER }}
      JENKINS_TOKEN: ${{ secrets.JENKINS_TOKEN }}
