name: Clean Image Registry

on: 
  workflow_call:
    inputs:
      image_name: 
        description: "Image Name"
        required: true
        type: string
      prod_keep_at_least:
        description: "Minimum number of production images to retain"
        required: false
        type: number
        default: 10
      prod_cut_off:
        description: "Cut-off for production images (format as supported by python's dateparser)"
        required: false
        type: string
        default: "One month ago UTC" 
      testing_keep_at_least:
        description: "Minimum number of testing/staging images to retain"
        required: false
        type: number
        default: 5
      testing_cut_off:
        description: "Cut-off for testing/staging images (format as supported by python's dateparser)"
        required: false
        type: string
        default: "One week ago UTC"
    secrets:
      CLEANUP_TOKEN:
        description: Github token with permissions - read:packages, write:packages, delete-packages
        required: true

jobs:
  clean-ghcr-prod:
    name: Delete old unused container images
    runs-on: ubuntu-latest
    steps:
      - name: Delete old containers in Production
        id: list-deleted-packages-prod
        uses: artazar/container-retention-policy@keep_at_least_filtered
        with:
          cut-off: ${{ inputs.prod_cut_off }}
          account-type: org
          org-name: Calance-US
          filter_tags: "v*.*.*"
          image-names: ${{ inputs.image_name }}
          keep-at-least: ${{ inputs.prod_keep_at_least }}
          token: ${{ secrets.CLEANUP_TOKEN }}
  
  clean-ghcr-testing:
    name: Delete old unused container images
    runs-on: ubuntu-latest
    steps:
      - name: Delete old containers in Testing
        id: list-deleted-packages-testing
        uses: artazar/container-retention-policy@keep_at_least_filtered
        with:
          cut-off: ${{ inputs.testing_cut_off }}
          account-type: org
          org-name: Calance-US
          filter_tags: "rc*"
          image-names: ${{ inputs.image_name }}
          keep-at-least: ${{ inputs.testing_keep_at_least }}
          token: ${{ secrets.CLEANUP_TOKEN }}
        