---
name: Deploy to Kubernetes
on:
  workflow_call:
    inputs:
      repository_name:
        description: Name of the service to be deployed (usually it is the same as
          the repository name)
        required: true
        type: string
      image_name:
        description: Image name of our application's dockerfile
        required: true
        type: string
      release_name:
        description: Application release name
        required: false
        type: string
        default: "${{ github.event.repository.name }}"
      service_name:
        description: Application service name
        required: false
        type: string
        default: "${{ github.event.repository.name }}"
      cluster_environment:
        description: Cluster environment to deploy your image
        required: true
        type: string
      version:
        description: Application version
        required: true
        type: string
      commit_id:
        description: Latest commit SHA of the build
        required: true
        type: string
      env_specific_namespaces:
        description: 'Enable generating namespace value according to the cluster-environment
          (ex: assuming hrms namespace is configured, testing version will use hrms-testing
          as the namespace while production version will use hrms as the namespace'
        required: false
        type: boolean
        default: false
      image_registry:
        description: Name of Image Registry
        required: true
        type: string
      jenkins_job_name:
        description: Name of Jenkins Job Name
          For deployment to Nutanix & Atcost Cluster => kubernetes-deploy-on-nutanix
          For deployment to Finca Cluster => Finca Deployment
        required: true
        type: string
      workflows_release:
        description: Workflows Release Version of current deployment
          If you are using deploy.yml@v1.0.8, then workflows_release => v1.0.8
        required: true
        type: string
      helm_values_repository:
        description: Name of repo that has helm values files
        required: true
        type: string
    secrets:
      JENKINS_URL:
        required: true
        description: Jenkins URL
      JENKINS_USER:
        required: true
        description: Jenkins USER
      JENKINS_TOKEN:
        required: true
        description: Jenkins TOKEN
jobs:
  trigger-jenkins-job:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Jenkins Job
        uses: Calance-US/build-jenkins-job@main
        with:
          jenkins-url: ${{ secrets.JENKINS_URL }}
          jenkins-token: ${{ secrets.JENKINS_TOKEN }}
          user: ${{ secrets.JENKINS_USER }}
          job-path: job/${{ inputs.jenkins_job_name }}
          job-params: |-
            {
              "SERVICE_NAME" : "${{ inputs.service_name }}", 
              "RELEASE_NAME" : "${{ inputs.release_name }}", 
              "IMAGE_NAME" : "${{ inputs.image_name }}", 
              "CLUSTER_ENVIRONMENT": "${{ inputs.cluster_environment }}", 
              "VERSION": "${{ inputs.version }}", 
              "COMMIT_ID": "${{ inputs.commit_id }}",
              "IMAGE_REGISTRY": "${{ inputs.image_registry }}",
              "WORKFLOWS_RELEASE": "${{ inputs.workflows_release }}",
              "HELM_VALUES_REPOSITORY": "${{ inputs.helm_values_repository }}"
            }
