name: Deploy to Kubernetes

on:
  workflow_dispatch:
    inputs:
      repository_name:
        description: "name of the service to be deployed (usually it is the same as the repository name)"
        required: true
        type: string
      image_name:
        description: "name of the image to deployed (excluding the registry & owner details), ex: atcost-ospos"
        required: true
        type: string
      release_name:
        description: "name of the helm release to be created (should only contain alpha-numeric & hyphen characters)"
        required: false
        type: string
        default: ""
      cluster_environment:
        description: "environment where application will be deployed, ex: testing, production, etc."
        required: true
        type: choice
        options:
          - "testing"
          - "production"
      version:
        description: "application version"
        required: true
        type: string
      namespace:
        required: true
        description: "cluseter namespace in which application is going to depolyed"
        type: string

  workflow_call:
    inputs:
      repository_name:
        description: "repository name in which application code is present"
        required: true
        type: string
      image_name:
        description: "image name of our application's dockerfile"
        required: false
        type: string
        default: "${{ github.event.repository.name }}"
      release_name:
        description: 'application release name'
        required: false
        type: string
        default: ""
      cluster_environment:
        description: "Cluster environment to deploy your image"
        required: true
        type: string
      version:
        description: "application version"
        required: true
        type: string
    secrets:
      NAMESPACE:
        required: true
        description: "cluster namespace in which application is going to be deployed"
      JENKINS_URL:
        required: true
        description: "Jenkins URL"
      JENKINS_USER:
        required: true
        description: "Jenkins USER"
      JENKINS_TOKEN:
        required: true
        description: "Jenkins TOKEN"

jobs:
  trigger-jenkins-job:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Jenkins Job
        uses: Calance-US/build-jenkins-job@main
        with:
          jenkins-url: "${{ secrets.JENKINS_URL }}"
          jenkins-token: "${{ secrets.JENKINS_TOKEN }}"
          user: "${{ secrets.JENKINS_USER }}"
          job-path: "job/kubernetes-deploy-on-nutanix"
          job-params: '{"SERVICE_NAME" : "${{ inputs.repository_name }}", "RELEASE_NAME" : "${{ inputs.release_name }}", "IMAGE_NAME" : "${{ inputs.image_name }}", "CLUSTER_ENVIRONMENT": "${{ inputs.cluster_environment }}" , "VERSION": "${{ inputs.version }}", "NAMESPACE": "${{ inputs.namespace || secrets.NAMESPACE }}" }'
