name: Deploy to Kubernetes

on:
  workflow_dispatch:
    inputs:
      repository_name:
        description: 'Enter repository name:'
        required: true
        type: string
      cluster_environment:
        description: 'Which environment you want to deploy?'
        required: true
        type: choice
        options:
        - "testing"
        - "production"
      version:
        description: 'Enter the application version:'
        required: true
        type: string
      namespace:
        required: true
        description: 'Enter the application namespace:'
        type: string

  workflow_call:
    inputs:
      repository_name:
        description: 'Enter repository name:'
        required: true
        type: string
      cluster_environment:
        description: 'Which environment you want to deploy?'
        required: true
        type: string
      version:
        description: 'Enter the application version:'
        required: true
        type: string
    secrets:
      namespace:
        required: true
        description: 'Enter the application namespace:'

jobs:
  trigger-jenkins-job:
    runs-on: ubuntu-latest
    steps:
      - name: Save JENKINS values
        shell: bash
        env:
          JENKINS_URL: ${{ secrets.JENKINS_URL }}
          JENKINS_USER: ${{ secrets.JENKINS_USER }}
          JENKINS_TOKEN: ${{ secrets.JENKINS_TOKEN }}
        run: |
          echo "$JENKINS_URL"
          echo "$JENKINS_USER"
      - name: Trigger Jenkins Job
        uses: prempratap09/build-jenkins-job@master
        with:
          jenkins-url: $JENKINS_URL
          jenkins-token: $JENKINS_TOKEN
          user: $JENKINS_USER
          job-path: "job/kubernetes-deploy-on-nutanix"
          job-params: '{"SERVICE_NAME" : "${{ inputs.repository_name }}", "CLUSTER_ENVIRONMENT": "${{ inputs.cluster_environment }}" , "VERSION": "${{ inputs.version }}", "NAMESPACE": "${{ secrets.namespace }}" }'
