name: TestCase 6 - Image Cleanup Pipeline

on: workflow_dispatch
    
jobs:
  list-packages:
    runs-on: ubuntu-latest
    outputs:
      packages: ${{ steps.list-packages.outputs.result }}
    steps:
      - uses: actions/github-script@v6
        id: list-packages
        with:
          github-token: ${{ secrets.IMAGE_CLEANUP_TOKEN }}
          script: | 
            const resp = await github.paginate(
              'GET /orgs/Calance-US/packages', 
              {
                package_type: 'container',
                visibility: 'private'
              }
            );

            return resp.map(package => package.name);

  delete-packages:
    needs: list-packages
    uses: ./.github/workflows/clean-image-registry.yml
    with:
      image_name: ${{ needs.list-packages.outputs.packages}}
      prod_keep_at_least: 5
      prod_cut_off: "1 month ago UTC"
      testing_keep_at_least: 2
      testing_cut_off: "1 week ago UTC"
      non_semver_keep_at_least: 2
      non_semver_cut_off: "1 week ago UTC"
      untagged_cut_off: untagged_cut_off
    secrets: 
      IMAGE_CLEANUP_TOKEN: ${{ secrets.IMAGE_CLEANUP_TOKEN }}
      MS_TEAMS_WEBHOOK_URI: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
