name: Testing the Image Cleanup Pipeline
on:
  push: 
    branches:
      - "task/*"

jobs:
  build-packages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository (clone the repo for use)
        uses: actions/checkout@v3
      - name: Log in to github Container registry where image is pushed and pulled from
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: ${{ secrets.REPOSITORY_OWNER }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Build and push Docker image to github container registry
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: "ghcr.io/calance-us/calance-workflows:v1.2.1-rc1,ghcr.io/calance-us/calance-workflows:v1.7.1-rc1,ghcr.io/calance-us/calance-workflows:v1.8.2-rc1,ghcr.io/calance-us/calance-workflows:v1.8.1-rc1,ghcr.io/calance-us/calance-workflows:v1.3.1-rc1,ghcr.io/calance-us/calance-workflows:v1.3.7-rc1"
          labels: ${{ steps.meta.outputs.labels }}


  delete-packages:
    uses: ./.github/workflows/clean-image-registry.yml
    with:
      image_name: calance-workflows
      prod_keep_at_least: 10
      prod_cut_off: "1 month ago UTC"
      testing_keep_at_least: 5
      testing_cut_off: "1 week ago UTC"
    secrets: 
      IMAGE_CLEANUP_TOKEN: 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
      MS_TEAMS_WEBHOOK_URI: https://calance1.webhook.office.com/webhookb2/7c2c62a9-70dd-43dd-8fd1-93f026d3dea4@d8a741e9-a9f4-417c-bf71-a407a2f601b8/IncomingWebhook/033d52f158a2474a89b77cdeaf4889ec/ab57efb7-c635-4785-917f-8543e61a3290
