name: TestCase 1 - Basic Repository
on:
  push:
    branches: ["919-support-for-multiple-image-registries"]

jobs:
  build-and-push-dockerimages:
    uses: ./.github/workflows/build.yml
    with:
      image_name: calance-workflows
    secrets:
      IMAGE_REGISTRY_PASSWORD: ${{ secrets.GHCR_TOKEN }}
      
  # deploy-to-kubernetes:
  #   needs: build-and-push-dockerimages
  #   strategy:
  #     fail-fast: false
  #   permissions:
  #     contents: read
  #     packages: write
  #   uses: ./.github/workflows/deploy.yml
  #   with:
  #     repository_name: ${{ github.event.repository.name }}
  #     version: ${{ needs.build-and-push-dockerimages.outputs.version }}
  #     cluster_environment: ${{ needs.build-and-push-dockerimages.outputs.cluster_environment }}
  #     image_registry: ${{ vars.IMAGE_REGISTRY }}
  #     image_registry_username: ${{ vars.IMAGE_REGISTRY_USERNAME }}
  #   secrets:
  #     JENKINS_URL: ${{ secrets.JENKINS_URL }}
  #     JENKINS_USER: ${{ secrets.JENKINS_USER }}
  #     JENKINS_TOKEN: ${{ secrets.JENKINS_TOKEN }}
